CREATE DATABASE users;
use users;

create table emails(
   user_id int auto_increment primary key,
   user_name varchar(20) not null,
   user_email varchar(50) not null,
   unique (user_name, user_email)
);

insert into emails (user_name, user_email)
values
("turnarose","jbutt@gmail.com"),
("rwandanfettuccine","josephine_darakjy@darakjy.org"),
("jonastripp","art@venere.org"),
("nagscurvy","lpaprocki@hotmail.com"),
("squigglygreen","donette.foller@cox.net"),
("shortlyoftentimes","simona@morasca.com"),
("irkpair","mitsue_tollner@yahoo.com"),
("hippiesresolve","leota@hotmail.com"),
("lacombesmallweed","sage_wieser@cox.net"),
("morosecogs","kris@gmail.com"),
("heftybotanical","minna_amigon@yahoo.com"),
("trentaller","amaclead@gmail.com"),
("coveringscale","kiley.caldarera@aol.com"),
("denimdocument","gruta@cox.net"),
("rnacairn","calbares@gmail.com"),
("judyorrin","mattie@aol.com"),
("claykick","meaghan@hotmail.com"),
("chevroletoptimism","gladys.rim@rim.org"),
("brilliantreining","yuki_whobrey@aol.com"),
("slingfiftieth","fletcher.flosi@yahoo.com"),
("ownerstables","bette_nicka@cox.net"),
("pausegrass","vinouye@aol.com"),
("dragonflyoperate","willard@hotmail.com"),
("blankdodgy","mroyster@royster.com"),
("minutesarchive","alisha@slusarski.com"),
("sensitivewiping","allene_iturbide@cox.net"),
("trenddragonish","chanel.caudy@caudy.org"),
("arnielupus","ezekiel@chui.com"),
("strangeletdown","wkusko@yahoo.com"),
("winephoney","bfigeroa@aol.com"),
("piespresso","ammie@corrio.com"),
("familysurmise","francine_vocelka@vocelka.com"),
("bricklondon","ernie_stenseth@aol.com"),
("convectionblackfish","albina@glick.com"),
("homerunrailroad","asergi@gmail.com"),
("pensivefactor","solange@shinko.com"),
("bennyobject","jose@yahoo.com"),
("enquirersector","rozella.ostrosky@ostrosky.com"),
("outsidesilicon","valentine_gillian@gmail.com"),
("twinklecruelness","kati.rulapaugh@hotmail.com"),
("humansalt","youlanda@aol.com"),
("jupetrolling","doldroyd@aol.com"),
("snowplowcawn","roxane@hotmail.com"),
("iphoneunion","lperin@perin.org"),
("pumicerelay","erick.ferencz@aol.com"),
("pazytaylor","fsaylors@saylors.org"),
("pyroxenedartle","jina_briddick@briddick.com"),
("occultationcanal","kanisha_waycott@yahoo.com"),
("bakeshopfeeble","emerson.bowley@bowley.org"),
("bostonwill","bmalet@yahoo.com"),
("moughvoid","bbolognia@yahoo.com"),
("deforestshaggy","lnestle@hotmail.com"),
("shamcoot","sabra@uyetake.org"),
("subleasecrow","mmastella@mastella.com"),
("extractsomen","karl_klonowski@yahoo.com"),
("manyjones","twenner@aol.com"),
("embezzlelebanese","amber_monarrez@monarrez.org"),
("skinlessguess","shenika@gmail.com"),
("lucknowmast","delmy.ahle@hotmail.com"),
("carriedexpansive","deeanna_juhas@gmail.com"),
("presleydigress","bpugh@aol.com"),
("fermentorella","jamal@vanausdal.org"),
("penberthhurried","cecily@hollack.org"),
("ghostroping","carmelina_lindall@lindall.com"),
("puzzledbuzz","maurine_yglesias@yglesias.com"),
("clunkure","tawna@gmail.com"),
("heartyoverlook","penney_weight@aol.com"),
("blinkingwarming","elly_morocco@gmail.com"),
("shellfishextension","ilene.eroman@hotmail.com"),
("pigjumpgrief","vmondella@mondella.com"),
("lyricistchopsticks","kallie.blackwood@gmail.com"),
("reputableabrasion","johnetta_abdallah@aol.com"),
("forgivereservoir","brhym@rhym.com"),
("chompsister","micaela_rhymes@gmail.com"),
("chunkymoyles","tamar@hotmail.com"),
("excuseparker","moon@yahoo.com"),
("screechshaky","laurel_reitler@reitler.com"),
("screenhover","delisa.crupi@crupi.com"),
("rhymemasculine","viva.toelkes@gmail.com"),
("landsideachernar","elza@yahoo.com"),
("dequeuepebble","devorah@hotmail.com"),
("riflefarrum","timothy_mulqueen@mulqueen.org"),
("buddycound","ahoneywell@honeywell.com"),
("glimmermoustache","dominque.dickerson@dickerson.org"),
("relaxred","lettie_isenhower@yahoo.com"),
("earbywhinny","mmunns@cox.net"),
("laramixture","stephaine@barfield.com"),
("tethyswooden","lai.gato@gato.org"),
("britishstage","stephen_emigh@hotmail.com"),
("gripperyresurrect","tshields@gmail.com"),
("mingedictator","twardrip@cox.net"),
("bristollinguist","cory.gibes@gmail.com"),
("bullseyearizona","danica_bruschke@gmail.com"),
("troutcrashing","wilda@cox.net"),
("lussanlanky","elvera.benimadho@cox.net"),
("dillantsy","carma@cox.net"),
("greeterpaying","malinda.hochard@yahoo.com"),
("swacketmaterial","natalie.fern@hotmail.com"),
("dresspreface","lisha@centini.org");

select * from emails;